package com.pahanaedu.bookshop.persistence.reports.util;

import com.pahanaedu.bookshop.persistence.reports.dto.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Utility class for formatting reports
 * Uses the same database connection pattern as existing code
 */
public class ReportFormatter {
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private static final SimpleDateFormat DISPLAY_DATE_FORMAT = new SimpleDateFormat("MMM dd, yyyy");

    /**
     * Format ReportDTO to HTML string
     */
    public static String formatReportToHTML(ReportDTO report) {
        if (report == null) {
            return "<p>No report data available</p>";
        }

        StringBuilder html = new StringBuilder();
        
        // Report header
        html.append("<div class='report-header'>");
        html.append("<h1 class='report-title'>").append(report.getReportTitle()).append("</h1>");
        html.append("<p class='report-subtitle'>Pahana Edu Book Shop</p>");
        html.append("</div>");
        
        // Report info
        html.append("<div class='report-info'>");
        html.append("<div><strong>Generated:</strong> ").append(DATE_FORMAT.format(report.getGeneratedAt())).append("</div>");
        html.append("<div><strong>Report Type:</strong> ").append(report.getReportType()).append("</div>");
        if (report.getGeneratedBy() != null) {
            html.append("<div><strong>Generated By:</strong> ").append(report.getGeneratedBy()).append("</div>");
        }
        html.append("</div>");
        
        // Summary section
        if (report.getSummary() != null) {
            html.append("<div class='summary-section'>");
            html.append("<div class='summary-title'>Report Summary</div>");
            html.append("<div class='summary-grid'>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getSummary().getTotalRecords()).append("</div>");
            html.append("<div class='summary-label'>Total Records</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>$").append(String.format("%.2f", report.getSummary().getTotalValue())).append("</div>");
            html.append("<div class='summary-label'>Total Value</div>");
            html.append("</div>");
            html.append("</div>");
            html.append("</div>");
        }
        
        // Data section
        html.append("<div class='data-section'>");
        html.append("<h3>Report Data</h3>");
        html.append("<p>Data is available in the report object</p>");
        html.append("</div>");
        
        // Footer
        html.append("<div class='footer'>");
        html.append("<p>This report was generated automatically by Pahana Edu Book Shop Management System</p>");
        html.append("<p>© ").append(new Date().getYear() + 1900).append(" Pahana Edu Book Shop. All rights reserved.</p>");
        html.append("</div>");
        
        return html.toString();
    }

    /**
     * Format CustomerReportDTO to HTML string
     */
    public static String formatCustomerReportToHTML(CustomerReportDTO report) {
        if (report == null || report.getCustomers() == null) {
            return "<p>No customer data available</p>";
        }

        StringBuilder html = new StringBuilder();
        
        // Report header
        html.append("<div class='report-header'>");
        html.append("<h1 class='report-title'>Customer Report</h1>");
        html.append("<p class='report-subtitle'>Pahana Edu Book Shop</p>");
        html.append("</div>");
        
        // Report info
        html.append("<div class='report-info'>");
        html.append("<div><strong>Generated:</strong> ").append(DATE_FORMAT.format(report.getGeneratedAt())).append("</div>");
        html.append("<div><strong>Report Type:</strong> Customer Management</div>");
        html.append("</div>");
        
        // Customer summary
        if (report.getCustomerSummary() != null) {
            html.append("<div class='summary-section'>");
            html.append("<div class='summary-title'>Customer Summary</div>");
            html.append("<div class='summary-grid'>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getCustomerSummary().getTotalCustomers()).append("</div>");
            html.append("<div class='summary-label'>Total Customers</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getCustomerSummary().getActiveCustomers()).append("</div>");
            html.append("<div class='summary-label'>Active Customers</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getCustomerSummary().getNewCustomersThisMonth()).append("</div>");
            html.append("<div class='summary-label'>New This Month</div>");
            html.append("</div>");
            html.append("</div>");
            html.append("</div>");
        }
        
        // Customer table
        html.append("<table class='data-table'>");
        html.append("<thead><tr>");
        html.append("<th>Name</th>");
        html.append("<th>Email</th>");
        html.append("<th>Phone</th>");
        html.append("<th>Address</th>");
        html.append("<th>Registration Date</th>");
        html.append("</tr></thead><tbody>");
        
        for (var customer : report.getCustomers()) {
            html.append("<tr>");
            html.append("<td>").append(customer.getName() != null ? customer.getName() : "N/A").append("</td>");
            html.append("<td>").append(customer.getEmail() != null ? customer.getEmail() : "N/A").append("</td>");
            html.append("<td>").append(customer.getTelephone() != null ? customer.getTelephone() : "N/A").append("</td>");
            html.append("<td>").append(customer.getAddress() != null ? customer.getAddress() : "N/A").append("</td>");
            html.append("<td>").append(customer.getCreatedAt() != null ? DISPLAY_DATE_FORMAT.format(customer.getCreatedAt()) : "N/A").append("</td>");
            html.append("</tr>");
        }
        
        html.append("</tbody></table>");
        
        // Footer
        html.append("<div class='footer'>");
        html.append("<p>This report was generated automatically by Pahana Edu Book Shop Management System</p>");
        html.append("<p>© ").append(new Date().getYear() + 1900).append(" Pahana Edu Book Shop. All rights reserved.</p>");
        html.append("</div>");
        
        return html.toString();
    }

    /**
     * Format BookReportDTO to HTML string
     */
    public static String formatBookReportToHTML(BookReportDTO report) {
        if (report == null || report.getBooks() == null) {
            return "<p>No book data available</p>";
        }

        StringBuilder html = new StringBuilder();
        
        // Report header
        html.append("<div class='report-header'>");
        html.append("<h1 class='report-title'>Book Inventory Report</h1>");
        html.append("<p class='report-subtitle'>Pahana Edu Book Shop</p>");
        html.append("</div>");
        
        // Report info
        html.append("<div class='report-info'>");
        html.append("<div><strong>Generated:</strong> ").append(DATE_FORMAT.format(report.getGeneratedAt())).append("</div>");
        html.append("<div><strong>Report Type:</strong> Inventory Management</div>");
        html.append("</div>");
        
        // Book summary
        if (report.getBookSummary() != null) {
            html.append("<div class='summary-section'>");
            html.append("<div class='summary-title'>Inventory Summary</div>");
            html.append("<div class='summary-grid'>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getBookSummary().getTotalBooks()).append("</div>");
            html.append("<div class='summary-label'>Total Books</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getBookSummary().getAvailableBooks()).append("</div>");
            html.append("<div class='summary-label'>Available</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>").append(report.getBookSummary().getOutOfStockBooks()).append("</div>");
            html.append("<div class='summary-label'>Out of Stock</div>");
            html.append("</div>");
            html.append("<div class='summary-item'>");
            html.append("<div class='summary-number'>$").append(String.format("%.2f", report.getBookSummary().getTotalInventoryValue())).append("</div>");
            html.append("<div class='summary-label'>Total Value</div>");
            html.append("</div>");
            html.append("</div>");
            html.append("</div>");
        }
        
        // Book table
        html.append("<table class='data-table'>");
        html.append("<thead><tr>");
        html.append("<th>Title</th>");
        html.append("<th>Author</th>");
        html.append("<th>ISBN</th>");
        html.append("<th>Category</th>");
        html.append("<th>Price</th>");
        html.append("<th>Quantity</th>");
        html.append("<th>Status</th>");
        html.append("</tr></thead><tbody>");
        
        for (var book : report.getBooks()) {
            String status = book.getQuantity() > 0 ? "Available" : "Out of Stock";
            String statusClass = book.getQuantity() > 0 ? "status-available" : "status-outofstock";
            
            html.append("<tr>");
            html.append("<td>").append(book.getTitle() != null ? book.getTitle() : "N/A").append("</td>");
            html.append("<td>").append(book.getAuthor() != null ? book.getAuthor() : "N/A").append("</td>");
            html.append("<td>").append(book.getIsbn() != null ? book.getIsbn() : "N/A").append("</td>");
            html.append("<td>").append(book.getCategory() != null ? book.getCategory() : "N/A").append("</td>");
            html.append("<td>$").append(book.getPrice() != null ? book.getPrice().toString() : "0.00").append("</td>");
            html.append("<td>").append(book.getQuantity()).append("</td>");
            html.append("<td class='").append(statusClass).append("'>").append(status).append("</td>");
            html.append("</tr>");
        }
        
        html.append("</tbody></table>");
        
        // Footer
        html.append("<div class='footer'>");
        html.append("<p>This report was generated automatically by Pahana Edu Book Shop Management System</p>");
        html.append("<p>© ").append(new Date().getYear() + 1900).append(" Pahana Edu Book Shop. All rights reserved.</p>");
        html.append("</div>");
        
        return html.toString();
    }
} 